#! /bin/bash

if [[ $1 > 0 ]]; then
  echo "setting screenlock to true";
  sudo osascript -e 'tell application "System Events" to set require password to wake of security preferences to true';
else
  echo "setting screenlock to false";
  sudo osascript -e 'tell application "System Events" to set require password to wake of security preferences to false';
fi;
